name: flutter android deploy dev

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: prepare
    env:
      STORE_FILE: /tmp/qa.keystore
    steps:
      - name: set up key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: get dependencies
        run: flutter pub get
      - name: check
        run: |
          flutter analyze
          flutter test
      - name: install libssl
        run: sudo apt install libssl-dev
      - name: decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | openssl enc -d -base64 > $STORE_FILE

      - name: build
        run:  flutter build appbundle --obfuscate --build-number $GITHUB_RUN_NUMBER --flavor <???> --release --dart-define=PARAM=<???> --split-debug-info ./build/debuginfo
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASS: ${{ secrets.STORE_PASS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
      - name: upload
        run: |
            cd android
            ./gradlew appDistributionUpload<???>Release
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}

      - name: notify result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: githubActionsNotify
          SLACK_TITLE: Workflow Result
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.DEV_SLACK_WEBHOOK }}
